name: budget_optimization
services:
  dev:
    image: budget_optimization-dev:latest
    build:
      context: .
      dockerfile: Dockerfile/dev.Dockerfile
    volumes:
      - type: bind
        source: /home/ubuntu/workspaces/budget_optimization
        target: /home/ubuntu/budget_optimization
    working_dir: /home/ubuntu/budget_optimization
  prod:
    image: budget_optimization-prod:latest
    build:
      context: .
      dockerfile: Dockerfile/prod.Dockerfile
